services:
  directus:
    image: directus/directus:11.3.4
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "f$Dbuc8Zh9UW&r"
      ADMIN_EMAIL: "test@test.com"
      ADMIN_PASSWORD: "interview"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      PUBLIC_URL: "http://localhost:8055"
      DIRECTUS_CORS: "http://localhost:3000"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:3000"
      CORS_METHODS: "GET,POST,PUT,DELETE"
      CORS_ALLOWED_HEADERS: "Content-Type, Authorization"
      CORS_ALLOW_CREDENTIALS: "true"
